name: check-main-branch
on: 
  push:
  workflow_dispatch:

# This branch is not main - String will not be printed.
jobs:
  check-main-branch:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the main branch."